version: "1"
defaults:
  app_name: stageorders
services:
  stageorders:
    image: centos:7
    ports:
      - "3000:3000"
      - "5000:5000"
      - "8080:80"
    working_dir: "/var/www/{{ app_name }}"
    user: "{{ app_name }}"
    command: ["/usr/bin/dumb-init", '/home/{{ app_name }}/.rbenv/shims/foreman', 'start']
    dev_overrides:
      environment:
        - "DEBUG=1"
      command: ["/usr/bin/dumb-init", '/bin/bash', '/app/ansible/sleep-loop.sh']
      volumes:
        - "$PWD:/app"
registries: {}
