---
- hosts: all
  gather_facts: false
  become: yes
  vars:
    package_manager: yum
    nodejs_version: v0.10.4
    ruby_version: 2.3.1
    rails_version: 5.0.0.1
    domainname: localhost
    app_name: stageorders
    app_user: stageorders
    app_path: /var/www/{{ app_name }}
  roles:
    - role: geerlingguy.apache
  tasks:
    - name: Install dumb init
      get_url: dest=/usr/bin/dumb-init url=https://github.com/Yelp/dumb-init/releases/download/v1.0.2/dumb-init_1.0.2_amd64 mode=0775 validate_certs=no
    - include: tasks/devtools.yml
    - include: tasks/apache.yml
    - include: tasks/nodejs.yml
    - include: tasks/app_user.yml
    - include: tasks/ruby.yml
      remote_user : "{{ app_user }}"
