---
- hosts: all
  remote_user: vagrant
  become: yes
  vars:
    package_manager: yum
    nodejs_version: v0.10.4
    ruby_version: 2.3.1
    rails_version: 5.0.0.1
    domainname: localhost
    app_name: stageorders
    app_user: vagrant
    app_path: /var/www/{{ app_name }}
  tasks:
    - include: tasks/devtools.yml
    - include: tasks/nodejs.yml
    - include: tasks/ruby.yml
      become : "{{ app_user }}"
