---
- hosts: all
  remote_user: vagrant
  become: yes
  vars:
    app_user: vagrant
  tasks:
    - include: tasks/devtools.yml
    - include: tasks/nodejs.yml
    - include: tasks/ruby.yml
      become : "{{ app_user }}"
