## Add the app users
- group: name=devs state=present
- user: name={{ app_user }} comment='App Server User' uid=1040 groups=devs,wheel
- file: path=/home/{{ app_user }}/.bashrc owner={{ app_user }} group={{ app_user }} mode=0755
- file: path=/home/{{ app_user }}/.bash_profile owner={{ app_user }} group={{ app_user }} mode=0755
