## Add the app users
- name: Create devs group
  group:
    name: devs
    state: present
- name: Create application server user
  user:
    name: "{{ app_user }}"
    comment: 'App Server User'
    shell: /bin/bash
    groups: devs,wheel
- name: Create .bashrc file
  file:
    path: "/home/{{ app_user }}/.bashrc"
#    owner: "{{ app_user }}"
#    group: "{{ app_user }}"
#    mode: 0755
    state: touch
- name: Create .bash_profile file
  file:
    path: "/home/{{ app_user }}/.bash_profile"
#    owner: "{{ app_user }}"
#    group: "{{ app_user }}"
#    mode: 0755
    state: touch
- name: Change directory attributes
  file:
    path: "/home/{{ app_user }}"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0755
    recurse: yes
    state: directory
